<?php
    echo"<div class='row'> 
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-primary btn-sm' type='button' onclick=\"shiftdataV2('client_profile.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Client Details</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-secondary btn-sm' type='button' onclick=\"shiftdataV2('client_appointments.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Appointments</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-tertiary btn-sm' type='button' onclick=\"shiftdataV2('client_package_schedule.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Package Schedules</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-secondary btn-sm' type='button' onclick=\"shiftdataV2('client_notes.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Notes</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-primary btn-sm' type='button' onclick=\"shiftdataV2('client_info_sheet.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Info Sheet</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-secondary btn-sm' type='button' onclick=\"shiftdataV2('client_hcp_budget.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>HCP Budget</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-tertiary btn-sm' type='button' onclick=\"shiftdataV2('client_agreement.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Agreement</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-secondary btn-sm' type='button' onclick=\"shiftdataV2('client_contacts.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Contacts</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-primary btn-sm' type='button' onclick=\"shiftdataV2('client_support_plan.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Support Plan</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-secondary btn-sm' type='button' onclick=\"shiftdataV2('client_emergency_plan.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Emergency Plan</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-tertiary btn-sm' type='button' onclick=\"shiftdataV2('client_documents.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>Documents</button></div>
        <div class='col-4 col-md-2' style='text-align:center;padding:5px'><button class='btn btn-outline-secondary btn-sm' type='button' onclick=\"shiftdataV2('client_ndis_budget.php?sheba=$sheba&utype=$utype&sourceid=leads&url=".$_GET["url"]."&id=".$_GET["id"]."', 'datatableX')\" style='width:100%'>PLAN Budget</button></div>
    </div><br>";
?>